# Install script for directory: C:/Users/k/cs275/bullet/Demos

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/BULLET_PHYSICS")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/HelloWorld/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/OpenGL/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/AllBulletDemos/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/CcdPhysicsDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ConstraintDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/SliderConstraintDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/GenericJointDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/Raytracer/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/RagdollDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ForkLiftDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/BasicDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/VoronoiFractureDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/FractureDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/Box2dDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/BspDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/MovingConcaveDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/VehicleDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/CharacterDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/SoftDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/HeightFieldFluidDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/SimplexDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/DynamicControlDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ConvexHullDistance/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/DoublePrecisionDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ConcaveDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/CollisionDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ContinuousConvexCollision/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/GjkConvexCastDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/MultiMaterialDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/SerializeDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/InternalEdgeDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/MultiThreadedDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ParticlesOpenCL/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/OpenCLClothDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/Benchmarks/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/ThreadingDemo/cmake_install.cmake")
  INCLUDE("C:/Users/k/cs275/vs2010/Demos/VectorAdd_OpenCL/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

